//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoriAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public int ChapterId { get; set; }
        public string ChapterName { get; set; }
        public string ChapterText { get; set; }
        public int ChapterNo { get; set; }
        public int RelatedBook { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
