//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoriAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int CommentOwner { get; set; }
        public string CommentText { get; set; }
        public int BookPoint { get; set; }
        public int RelatedBook { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
